[App-265] 학생증 QR 코드 코드 블록 처리
uoslife/rebuild-client pull request #308
Opened 2024-01-27 14:49 UTC by ratafa

## Key Changes
- 포털 학번이 잘못 긁혀오는 현상이 있어, 학생증 Qr 코드를 임시적으로 블록 처리합니다. 

## Details
- QR과 관련된 코드들을 블록 처리했습니다.
- QR 코드 및 페이코 버튼이 사라짐에 따라, 스크린 상단 패딩값을 조절했습니다.
- Toast 메시지를 추가했습니다.
![2024-01-27_23-49-02](https://github.com/uoslife/rebuild-client/assets/89263598/e0a475c0-6f8c-4a93-922d-6fc62a5d9a7c)

## Allocated Issue
- close #307

2024-01-28 15:22 UTC, eunbae0 requested changes

2024-01-28 15:22 UTC, eunbae0 commented on src/screens/StudentIdScreen.tsx
> +  }, []);
혹시 useFocusEffect나 ussIsFocused를 사용하는건 불가능한가요?
```typescript
useFocusEffect(() => {});
const isFocused = useIsFocused();
```

2024-01-28 15:26 UTC, eunbae0 commented on src/screens/StudentIdScreen.tsx
> +  // };
여유되면 이거 utils/폴더로 분리한 다음 주석처리해도 좋을듯합니당

2024-01-28 17:57 UTC, ratafa commented on src/screens/StudentIdScreen.tsx
> +  }, []);
음 찾아보니 공식 문서에서는 navigation.listener보다는 useFocusEffect를 추천하고 있네염
useFocusEffect와 useIsFocused의 차이점은 리렌더링을 발생시키냐 아니냐의 차이네요
useIsFocused가 useEffect와 함께 쓰이면서 리렌더링을 발생시킵니다. 
현재 학생증 페이지는 리렌더링을 발생시킬 이유가 없으니 useFocusEffect를 사용하는게 좋을 것 같네요~

<출처>
https://reactnavigation.org/docs/use-focus-effect
https://reactnavigation.org/docs/use-is-focused

2024-01-28 17:57 UTC, ratafa commented on src/screens/StudentIdScreen.tsx
> +  // };
vamos

2024-01-29 22:58 UTC, eunbae0 approved these changes
GOOD~

2024-01-29 22:58 UTC, merged